#!/bin/bash

ListenIP=127.0.33.
DockerHome=/projects
DTUNHome=/opt/dt
DockerComposeHome=$DTUNHome/data
UseApacheReverseProxy=0
ExternalInterface=eth0

if [ -n "$DTUN_HOME" ];then
    DTUNHome=$DTUN_HOME
fi;
if [ -n "$DTUN_PROJECTS" ]; then
    DockerHome=$DTUN_PROJECTS
fi;
if [ -n "$DTUN_USE_REVERSE_PROXY" ]; then
    UseApacheReverseProxy=$DTUN_USE_REVERSE_PROXY
fi;
if [ -n "$DTUN_EXT_INTERFACE" ]; then
    ExternalInterface=$DTUN_EXT_INTERFACE
fi;

ExternalIp=`ip -br -4 addr show $ExternalInterface|awk '{ split(\$3, m, "/"); print m[1] }'`
env=$1
cmd=$2
params=""

if [ -z $cmd ]; then
    cmd=$1
else
    shift 2
    params=$@
fi;

# Finds first free IP in ListenIP zone
findFreeIp()
{
    min=1;
    lines=`netstat -an|grep -P "$ListenIP?:80"|grep LISTEN|awk '{split($4, r, ":"); split(r[1], r, "."); print r[4]}'|sort -n`
    while read number; do
	if [ -n "$number" ]; then
	    if [ $number -eq $min ]; then
		min=$(($number + 1))
	    fi;
	fi;
    done <<< "$lines"
    echo ${ListenIP}${min}
}
# Generates .env file
generateEnvFile()
{
    name=$1
    ip=$(findFreeIp)
    uid=$(id -u)
    gid=$(id -g)
    envFile=$DockerComposeHome/$name/.env
    configFile=$DockerComposeHome/$name/.config
    export LISTEN_IP=$ip USER_UID=$uid USER_GID=$gid && cat $configFile | envsubst > $envFile
}
# Generates .config file
generateConfigFile()
{
    name=$1
    ver_php=$2
    ver_mysql=$3
    config=$DockerComposeHome/$name/.config
    echo "# Build-only arguments">$config
    echo "PROJECT_NAME=$name">>$config
    echo "PHP_VERSION=$ver_php">>$config
    echo "MYSQL_VERSION=$ver_mysql">>$config
    echo "MYSQL_ROOT_PASSWORD=root">>$config
    echo "MYSQL_DATABASE=magento2">>$config
    echo "# Run-only arguments">>$config
    echo "LISTEN_IP=\${LISTEN_IP}">>$config
    echo "USER_UID=\${USER_UID}">>$config
    echo "USER_GID=\${USER_GID}">>$config
}

# Initializes docker environment
initializeDockerComposer()
{
    envName=$1
    shift 1
    ver_php=7.1
    ver_mysql=5.6
    for argument in $@; do
	case $argument in 
	    --mysql=*)
		ver_mysql="${argument#*=}"
		shift
	    ;;
	    --php=*)
		ver_php="${argument#*=}"
		shift
	    ;;
	esac;
    done 
    if [ -d $DockerHome/$envName ]; then
	echo "Initializing docker environment for $DockerHome/$envName in $DockerComposeHome..."
	mkdir -p $DockerComposeHome/$envName/data/mysql $DockerComposeHome/$envName/config
	find $DTUNHome/config -type d -links 2 -exec cp -r -t $DockerComposeHome/$envName/config {} +

	if [ ! -e $DockerComposeHome/$envName/data/html ]; then
	    ln -f -s $DockerHome/$envName $DockerComposeHome/$envName/data/html
	fi;
	cp $DTUNHome/config/docker-compose.yml $DockerComposeHome/$envName/docker-compose.yml
	generateConfigFile $envName $ver_php $ver_mysql
	generateEnvFile $envName
    else
	echo "FATAL: $DockerHome/$envName not found"
    fi;
}

# Starts docker environment
startDockerEnvironment()
{
    echo "Starting $1..."
    generateEnvFile $1
    cd $DockerComposeHome/$1 && docker-compose up --build -d
}
# Stops docker environment
stopDockerEnvironment()
{
    cd $DockerComposeHome/$1 && docker-compose down
}
# Generates hosts file
generateHostsFile()
{
    sed '/DTUNHostsStart/q' /etc/hosts
    generateHostsFileInsertion
    awk '/DTUNHostsEnd/,EOF' /etc/hosts
}
# Generates hosts list
generateHostsFileInsertion()
{
    cmd="docker ps --format '{{.Ports}} {{.Names}}'|grep web|awk 'BEGIN {ORS=\" \"}; {c=split(\$0, s); for(n=1; n<=c; n++) { if ((s[n] ~ \"$ListenIP*\") || (s[n] ~ \"web\")) print s[n]}; print \"\\n\"};'"
    list=$(eval $cmd)
    while read entry; do
	if [ -n "$entry" ]; then
	    ip=$(echo $entry|awk 'BEGIN {ORS=""}; {split($1, r, ":"); print r[1];};')
	    name=$(echo $entry|awk 'BEGIN {ORS=""}; {split($2, r, "-web"); print r[1];};')
	    echo "# DT $name"
	    echo -e "$ip\t$name.loc"
	    echo -e "$ip\tdc.$name.loc"
	    if [ -e "$DockerComposeHome/$name/config/php/aliases" ]; then
		while read line; do
		    echo -e "$ip\t$line"
		done < "$DockerComposeHome/$name/config/php/aliases"
	    fi;
	    echo "# /DT $name"
	fi;
    done <<< "$list"
}
#' Generates VHosts for reverse proxy
generateVHosts()
{
    cmd="docker ps --format '{{.Names}}'|grep web"
    list=$(eval $cmd)
    while read entry; do
	name=`echo $entry|awk '{split($1, m, "-web"); print m[1]; }'`
	export PROJECT_NAME=$name && cat $DTUNHome/config/php/vhost.conf|envsubst > /etc/apache2/sites-available/$name.conf
	sudo /usr/sbin/a2ensite $name
    done <<< "$list"
}
buildStyles()
{
    env=$1
    dir=$DockerHome/$env/vendor/snowdog/frontools
    if [ -d "$dir" ]; then
	cd $dir && npm update && npm run setup && npm run clean && npm run styles
    fi;
}
# Executes application on container
executeApp()
{
    env=$1
    cnt=$2
    chdir=$3
    shift 3
    app=$@
    cid="docker ps --format {{.ID}} --filter name=$env-$cnt"
    cid=$($cid)
    docker exec --workdir $chdir --user app -ti $cid $app
}

# CMD switch
case "$cmd" in
    attach)
	cd $DockerComposeHome/$env && docker-compose logs --tail=5 -f
    ;;
    dt-setup)
	chown :docker /etc/hosts
	chmod g=rw /etc/hosts
	added=`cat /etc/hosts|grep DTUNHostsStart`
	if [ -z "$added" ]; then
	    echo -e "\n# DTUNHostsStart\n# DTUNHostsEnd\n" >> /etc/hosts
	fi;
	if [ -d /etc/apache2 ]; then
	    chown :docker /etc/apache2/sites-available /etc/apache2/ports.conf
	    chmod g=rwX /etc/apache2/sites-available /etc/apache2/ports.conf
	    added=`cat /etc/sudoers|grep -e "%docker.*NOPASSWD.*apache2"`
	    if [ -z "$added" ]; then
		echo -e "\n# DTSudoersStart\n%docker ALL=NOPASSWD:/sbin/service apache2 reload\n%docker ALL=NOPASSWD:/usr/sbin/a2ensite \n# DTSudoersEnd\n">> /etc/sudoers
	    fi;
	fi; 
    ;;
    ddir)
	echo $DockerComposeHome/$env
    ;;
    rl)
	generateHostsFile > /tmp/hosts
	cp --preserve=mode,ownership /tmp/hosts /etc/hosts
	if [ $UseApacheReverseProxy -eq 1 ]; then
	    echo Reverse proxy reconfiguration to $ExternalIp
	    echo Listen $ExternalIp:80 >/etc/apache2/ports.conf
	    generateVHosts
	    sudo service apache2 reload && echo Reloaded Apache2
	fi;
    ;;
    p)
	sudo chown $(whoami):www-data -R $DockerHome/$env
    ;;
    styles)
	cd $DockerHome/$env/vendor/snowdog/frontools && gulp styles
    ;;
    mysql)
	executeApp $env mysql /var/lib/mysql mysql -u root -proot magento2
    ;;
    bash)
	executeApp $env web /var/www/html bash
    ;;
    mc)
	executeApp $env web /var/www/html mc
    ;;
    m2)
	executeApp $env web /var/www/html php bin/magento $params
    ;;
    idx)
	executeApp $env web /var/www/html php bin/magento indexer:reindex
    ;;
    git)
	cd $DockerHome/$env && git $params
    ;;
    composer)
	executeApp $env web /var/www/html composer $params
    ;;
    ci)
	executeApp $env web /var/www/html composer install -vvv
    ;;
    cu)
	executeApp $env web /var/www/html composer update
    ;;
    up)
	executeApp $env web /var/www/html php bin/magento setup:upgrade
	buildStyles $env
    ;;
    dep)
	executeApp $env web /var/www/html php vendor/bin/dep $params
    ;;
    init)
	initializeDockerComposer $env $params
    ;;
    start)
	startDockerEnvironment $env
    ;;
    stop)
	stopDockerEnvironment $env
    ;;
esac;
