version: '2'
services:
  web:
    container_name: ${PROJECT_NAME}-web
    ports:
      - "${LISTEN_IP}:80:80"
    cap_add:
      - SYS_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PHP_DEBUGGER=xdebug
      - PHP_MEMORY_LIMIT=-1
      - MAGENTO_MODE=${MAGENTO_MODE}
    volumes:
      - ../../data/html:/app
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
      - $HOME/.gitconfig:/root/.gitconfig
      - $HOME/.ssh/id_rsa:/home/application/.ssh/id_rsa
      - $HOME/.gitconfig:/home/application/.gitconfig
