version: '2'
services:
  web:
    container_name: ${PROJECT_NAME}-web
    ports:
      - "${LISTEN_IP}:80:80"
    cap_add:
      - SYS_ADMIN
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    volumes:
      - ../../data/html:/var/www/html
      - $HOME/.ssh/id_rsa:/var/www/.ssh/id_rsa
      - $HOME/.gitconfig:/var/www/.gitconfig
