version: '3'
services:
  redis:
    image: "redis:alpine"

  db:
    container_name: ${PROJECT_NAME}-db
    image: mysql:${IMAGE_MYSQL}
    volumes:
      - ./data/mysql:/var/lib/mysql  # Link to your local database, it will be imported when running.
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${LISTEN_IP}:3306:3306"

  mail:
    container_name: ${PROJECT_NAME}-mail
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  es:
    build:
      context: config/es
    container_name: ${PROJECT_NAME}-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - xpack.security.enabled=false
      - discovery.type=single-node

  web:
    container_name: ${PROJECT_NAME}-web
    ports:
      - "80:80"
    cap_add:
      - SYS_ADMIN
    build:
      context: config/php
      args:
        IMAGE_PHP: ${IMAGE_PHP}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - ./config/msmtp.conf:/etc/msmtp.conf
      - ./data/html:/var/www/html
      - $HOME/.ssh:/var/www/.ssh
      - $HOME/.gitconfig:/var/www/.gitconfig
    depends_on:
      - db
#      - mail
      - es
      - redis
