version: '2'
services:
  db:
    container_name: ${PROJECT_NAME}-db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../data/mysql:/var/lib/mysql  # Link to your local database, it will be imported when running.
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${LISTEN_IP}:3306:3306"